spring.application.name=${SPRING_APPLICATION_NAME:taskservice}

spring.datasource.url=${DB_URL}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}

jwt.secret=${JWT_SECRET}

server.port=${SERVER_PORT:8083}

eureka.client.service-url.defaultZone=${EUREKA_URL}

app.websocket.allowed-origins=${WEBSOCKET_ALLOWED_ORIGINS:http://localhost:5173}