spring.application.name=${SPRING_APPLICATION_NAME:monolith}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.datasource.url=${DB_URL}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}
server.port=${SERVER_PORT:8081}
client.uri=${CLIENT_URI:http://localhost:5173}
app.cookie.secure=${COOKIE_SECURE:false}
app.cookie.same-site=${COOKIE_SAME_SITE:Lax}
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI:http://localhost:8081/login/oauth2/code/google}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
app.websocket.allowed-origins=${WEBSOCKET_ALLOWED_ORIGINS:http://localhost:5173}