spring.application.name=${SPRING_APPLICATION_NAME:gateway}

server.port=${SERVER_PORT:8081}

spring.cloud.gateway.server.discovery.locator.enabled=${DISCOVERY_LOCATOR_ENABLED:true}
spring.cloud.gateway.discovery.locator.lower-case-service-id=${LOWER_CASE_SERVICE_ID:true}

eureka.client.service-url.defaultZone=${EUREKA_URL}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}