spring.application.name=authservice
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
REMOVED=${GOOGLE_CLIENT_SECRET}
spring.datasource.url=${POSTGRES_DB_URI}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.REMOVEDname=postgres
spring.datasource.password=REMOVED
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION_TIME}
server.port=${PORT}
logging.level.org.springframework.security=DEBUG