spring.application.name=authservice
spring.security.oauth2.client.registration.google.client-id=REMOVED
REMOVED=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
spring.datasource.url=jdbc:postgresql://localhost:5432/REMOVEDs
spring.jpa.hibernate.ddl-auto=update
spring.datasource.REMOVEDname=postgres
spring.datasource.password=REMOVED
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=REMOVED
jwt.expiration=900000
server.port=8000
logging.level.org.springframework.security=DEBUG