spring.application.name=workspaceservice
spring.datasource.url=${WORKSPACEDB_URI}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=${WORKSPACEDB_USERNAME}
spring.datasource.password=${WORKSPACEDB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=${JWT_SECRET}